config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :projects do
    resources :bugs
    resources :features
  end

  # resources :assigns
  # root "projects#index"

  post 'projects/:id', to: 'projects#show_button', as: :p

  devise_scope :user do
    # get 'sign_in', to: 'devise/sessions#new'
    root 'devise/sessions#new'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :assigns, dependent: :destroy
  has_many :users, through: :assigns

  has_many :bugs, dependent: :destroy
  has_many :features, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_project, only: [:show, :edit, :update, :destroy, :show_button]

  def index
    @projects = current_user.projects
  end

  def show
    @users = @project.users
    @available_users = User.where.not(id: @users)
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      Assign.new(user_id: current_user.id, project_id: Project.last.id).save
      redirect_to projects_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @project
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path, status: :see_other
  end

  def show_button
    authorize @project
    if params[:assign_user]
      Assign.new(user_id: params[:assign_user], project_id: params[:id]).save
    elsif params[:remove_user]
      @get_user = Assign.where(user_id: params[:remove_user], project_id: params[:id]).first
      @get_user.delete
    end
    redirect_to project_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def current_project
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Project</h3></div>
          <div class="card-body">
            <%= form_with model: @project do |form| %>
              <div>
                <%= form.label :title %><br />
                <%= form.text_field :title %>
                <% @project.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :description %><br />
                <%= form.text_area :description %><br />
                <% @project.errors.full_messages_for(:description).each do |message| %>
                <div><%= message %></div>
                <% end %>
              </div>

              <div><%= form.submit "Update Project", class: "btn btn-dark" %></div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<h1 class="mt-4 text-center">All Projects</h1>
<hr />

<% if policy(Project).show? %>
<h5 class="container">
  <%= link_to "Create a new project", new_project_path, class:
  "btn btn-primary" %>
</h5>
<% end %>
<br />
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    All Projects
  </div>

  <div class="card-body">
    <table id="datatablesSimple">
      <thead>
        <tr>
          <th>ID</th>
          <th>Project Title</th>
          <th>Project Description</th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %> <% @projects.each do |p| %>

        <tr>
          <td><%= count = count+1 %></td>
          <td><%# link_to p.title, project_path(p) %><%= p.title %></td>
          <td><%= p.description %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Project</h3></div>
          <div class="card-body">
            <%= form_with model: @project do |form| %>
              <div>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
                <% @project.errors.full_messages_for(:title).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :description %><br>
                <%= form.text_area :description %><br>
                <% @project.errors.full_messages_for(:description).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.submit "Create Project", class: "btn btn-dark" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% @new_project_flag = true %>

app/views/projects/show.html.erb
  <h1 class="mt-4 text-center"><%= @project.title %></h1>
  <hr />
  <% if policy(Project).show? %>
    <div class="d-flex justify-content-end">

      <%= link_to "Edit Project", edit_project_path, class: "btn btn-warning" %>
      &nbsp;&nbsp;&nbsp;
      <%= button_to "Delete Project", project_path, method: :delete, class: "btn btn-danger" %>

    </div>
  <% end %>
  <br />
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Project Info
    </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Project Title</th>
          <th>Project Description</th>
          <th>Assigned QAs</th>
          <th>Assigned Developers</th>
        </tr>
      </thead>
      <tbody>

        <tr>
          <td><%= @project.title %></td>
          <td><%= @project.description %></td>
          <td><table><tr><td><% @users.each do |u| %>
            <% if u.role == "qa" %>
              <%= u.email %>
              <br>
            <% end %>
          <% end %></td></tr></table></td>

          <td><table><tr><td><% @users.each do |u| %>
            <% if u.role == "developer" %>
              <%= u.email %>
              <br>
            <% end %>
          <% end %></td></tr></table></td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>

  <% if policy(Project).show? %>
  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Available Users
    </div>
    <div class="card-body">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Id</th>
            <th>User</th>
            <th>User Role</th>
            <% if policy(Project).show? %>
              <th>Action</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
            <% @available_users.each_with_index do |u, index| %>
            <% if u.role == "qa" or u.role == "developer" %>
            <tr>
              <td><%= index %></td>
              <td><%= u.email %></td>
              <td><%= u.role %></td>
              <td><%= button_to "Add", p_path(assign_user: u), method: :post, class: "btn btn-success" %></td>
            </tr>
            <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
    </div>
    <% end %>




  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Assigned Users
    </div>
    <div class="card-body">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Id</th>
            <th>User</th>
            <th>User Role</th>
            <% if policy(Project).show? %>
              <th>Action</th>
            <% end %>
          </tr>
        </thead>
        <tbody>

            <% count = 0 %> <% @users.each do |u| %>
            <% if u.role == "qa" or u.role == "developer" %>
            <tr>
              <td><%= count = count+1 %></td>
              <td><%= u.email %></td>
              <td><%= u.role %></td>
              <% if policy(Project).show? %>
                <td><%= button_to "Remove", p_path(remove_user: u), method: :post, class: "btn btn-danger" %></td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
    </div>