config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :projects do
    resources :bugs
    resources :features
  end

  # resources :assigns
  # root "projects#index"

  post 'projects/:id', to: 'projects#show_button', as: :p

  devise_scope :user do
    # get 'sign_in', to: 'devise/sessions#new'
    root 'devise/sessions#new'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user, optional: true

  enum status: {
    new_bug: 0,
    in_progress: 1,
    in_review: 2,
    fixed: 4
  }

  validates :title, presence: true
  validates :comment, presence: true, length: { minimum: 10 }

  validate :validate_user_role, if: :user

  private
  def validate_user_role
    return if user.developer? && project.users.include?(user)
    errors.add(:user_id, "User assigned on a project must be valid")
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_project, only: [:index, :show, :new, :create, :edit, :update]

  def index
    @bugs = Bug.where(project_id: @project.id)
  end

  def show
    @bug = Bug.find(params[:id])
    @bugs = Bug.where(project_id: @project.id)
  end

  def new
    @bug = Bug.new
    authorize @bug
    @users = @project.users
  end

  def create
    @users = @project.users
    @u = User.find_by(email: params[:bug][:user_id])
    params[:bug][:user_id] = @u.id
    params[:bug][:status] = :new_bug
    @bug = @project.bugs.new(bug_params)
    if @bug.save
      redirect_to project_bugs_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bug = Bug.find(params[:id])
    authorize @bug if @bug.status == 'fixed' or @bug.user_id != current_user.id
    @users = @project.users
  end

  def update
    @users = @project.users
    @u = User.find_by(email: params[:bug][:user_id])
    params[:bug][:user_id] = @u.id
    @bug = Bug.find(params[:id])
    if @bug.update(bug_params)
      redirect_to project_bugs_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    redirect_to project_bugs_path, status: :see_other
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :comment, :user_id, :status)
  end

  def current_project
    @project = Project.find(params[:project_id])
  end

end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Edit Bug</h3></div>
          <div class="card-body">
            <%= form_with model: ([@project, @bug]) do |form| %>
              <% if current_user.role != "developer" %>
                <div>
                  <%= form.label :title %><br>
                  <%= form.text_field :title %>
                  <% @bug.errors.full_messages_for(:title).each do |message| %>
                    <div><%= message %></div>
                  <% end %>
                </div>

                <div>
                  <%= form.label :comment %><br>
                  <%= form.text_area :comment %><br>
                  <% @bug.errors.full_messages_for(:comment).each do |message| %>
                    <div><%= message %></div>
                  <% end %>
                </div>

                <% arr = Array.new %>
                <% @users.each do |u| %>
                  <% if u.role == "developer" %>
                    <% arr.push(u.email) %>
                  <% end %>
                <% end %>

                <div class="field">
                  <%= form.label :user_id, "Bug Assigned To " %>
                  <%= form.select :user_id, arr %><br />
                </div>
              <% end %>
                <% if current_user.role == "developer" %>
                  <%= form.hidden_field :title, value: @bug.title %>
                  <%= form.hidden_field :comment, value: @bug.comment %>
                  <%= form.hidden_field :user_id, value: current_user.email %>

                  <% if @bug.status != "fixed" %>
                    <% if @bug.status == "new_bug" %>
                      <div class="field">
                        <%= form.label :status, "Bug Status " %>
                        <%= form.select :status, ["new_bug", "in_progress"] %><br />
                      </div>
                    <% elsif @bug.status == "in_progress" %>
                      <div class="field">
                        <%= form.label :status, "Bug Status " %>
                        <%= form.select :status, ["in_progress", "in_review"] %><br />
                      </div>
                    <% end %>
                  <% else %>
                    <div class="field">
                      <%= form.label :status, "Bug Status: "+ @bug.status %>
                    </div>
                  <% end %>
                <% end %>

                <% if current_user.role == "qa" %>
                  <% if @bug.status == "in_review"%>
                    <div class="field">
                      <%= form.label :status, "Bug Status " %>
                      <%= form.select :status, ["in_review", "fixed"] %><br />
                    </div>
                  <% else %>
                    <div class="field">
                      <%= form.label :status, "Bug Status: "+ @bug.status %>
                    </div>
                  <% end %>
                <% end %>

                <div>
                  <%= form.submit "Update Bug", class: "btn btn-dark" %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bugs/index.html.erb
<h1 class="mt-4 text-center">All Bugs</h1>
<hr />
<% if policy(Bug).index? %>
  <h5 class="container">
    <%= link_to "Create a bug", new_project_bug_path, class:
    "btn btn-primary" %>
  </h5>
<% end %>
<br />

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    All Bugs
  </div>

  <div class="card-body">
    <table id="datatablesSimple">
      <thead>
        <tr>
          <th>ID</th>
          <th>Bug Title</th>
          <th>Comment</th>
          <th>Bug Assigned to</th>
          <th>Bug Status</th>
        </tr>
      </thead>
      <tbody>
        <% @bugs.each_with_index do |bug, index| %>

        <tr>
          <td><%= index %></td>
          <td><%= bug.title %></td>
          <td><%= bug.comment %></td>
          <td><%= bug.user.email %></td>
          <td><%= bug.status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bugs/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Bug</h3></div>
          <div class="card-body">
            <%= form_with model: ([@project, @bug]) do |form| %>
              <div>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
                <% @bug.errors.full_messages_for(:title).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :comment %><br>
                <%= form.text_area :comment %><br>
                <% @bug.errors.full_messages_for(:comment).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <% arr = Array.new %>
              <% @users.each do |u| %>
                <% if u.role == "developer" %>
                  <% arr.push(u.email) %>
                <% end %>
              <% end %>

              <div class="field">
                <%= form.label :user_id, "Bug Assigned To " %>
                <%= form.select :user_id, arr %><br />
              </div>

              <div>
                <%= form.submit "Create Bug", class: "btn btn-dark" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bugs/show.html.erb
<h1 class="mt-4 text-center"><%= @bug.title %></h1>
<hr />
<% if policy(Bug).show? or @bug.status != "fixed" %>
  <div class="d-flex justify-content-end">
    <%= link_to "Edit Bug", edit_project_bug_path, class: "btn btn-warning" %>
      &nbsp;&nbsp;&nbsp;
    <% if policy(Bug).show? %>
      <%= button_to "Delete Bug", project_bug_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>
<br />
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    Bug Info
  </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Bug Title</th>
          <th>Comment</th>
          <th>Bug Assigned to</th>
          <th>Bug Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @bug.title %></td>
          <td><%= @bug.comment %></td>
          <td><%= @bug.user.email %></td>
          <td><%= @bug.status %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>