config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :projects do
    resources :bugs
    resources :features
  end

  # resources :assigns
  # root "projects#index"

  post 'projects/:id', to: 'projects#show_button', as: :p

  devise_scope :user do
    # get 'sign_in', to: 'devise/sessions#new'
    root 'devise/sessions#new'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :project
  belongs_to :user

  enum status: {
    new_feature: 0,
    in_progress: 1,
    in_review: 2,
    complete: 3
  }

  validates :title, presence: true
  validates :comment, presence: true, length: { minimum: 10 }

  validate :assigned_user_should_be_valid, if: :user

  private
  def assigned_user_should_be_valid
    return if user.developer? && project.users.include?(user)
    errors.add(:user_id, "User assigned on a project must be valid")
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :current_project, only: [:index, :show, :new, :create, :edit, :update]

  def index
    @features = Feature.where(project_id: @project.id)
  end

  def show
    @feature = Feature.find(params[:id])
    @features = Feature.where(project_id: @project.id)
  end

  def new
    @feature = Feature.new
    authorize @feature
    @users = @project.users
  end

  def create
    @users = @project.users
    @u = User.find_by(email: params[:feature][:user_id])
    params[:feature][:user_id] = @u.id
    params[:feature][:status] = 'new_feature'
    @feature = @project.features.new(feature_params)
    if @feature.save
      redirect_to project_features_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @feature = Feature.find(params[:id])
    authorize @feature if @feature.status == 'complete' or @feature.user_id != current_user.id
    @users = @project.users
  end

  def update
    @users = @project.users
    @u = User.find_by(email: params[:feature][:user_id])
    params[:feature][:user_id] = @u.id
    @feature = Feature.find(params[:id])
    if @feature.update(feature_params)
      redirect_to project_features_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy
    redirect_to project_features_path, status: :see_other
  end

  private

  def feature_params
    params.require(:feature).permit(:title, :comment, :user_id, :status)
  end

  def current_project
    @project = Project.find(params[:project_id])
  end

end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Edit Feature</h3></div>
          <div class="card-body">
            <%= form_with model: ([@project, @feature]) do |form| %>
              <% if current_user.role != "developer" %>
                <div>
                  <%= form.label :title %><br>
                  <%= form.text_field :title %>
                  <% @feature.errors.full_messages_for(:title).each do |message| %>
                    <div><%= message %></div>
                  <% end %>
                </div>

                <div>
                  <%= form.label :comment %><br>
                  <%= form.text_area :comment %><br>
                  <% @feature.errors.full_messages_for(:comment).each do |message| %>
                    <div><%= message %></div>
                  <% end %>
                </div>

                <% arr = Array.new %>
                <% @users.each do |u| %>
                  <% if u.role == "developer" %>
                    <% arr.push(u.email) %>
                  <% end %>
                <% end %>

                <div class="field">
                  <%= form.label :user_id, "Feature Assigned To " %>
                  <%= form.select :user_id, arr %><br />
                </div>
              <% end %>
                <% if current_user.role == "developer" %>
                  <%= form.hidden_field :title, value: @feature.title %>
                  <%= form.hidden_field :comment, value: @feature.comment %>
                  <%= form.hidden_field :user_id, value: current_user.email %>

                  <% if @feature.status != "complete" %>
                    <% if @feature.status == "new_feature" %>
                      <div class="field">
                        <%= form.label :status, "Feature Status " %>
                        <%= form.select :status, ["new_feature", "in_progress"] %><br />
                      </div>
                    <% elsif @feature.status == "in_progress" %>
                      <div class="field">
                        <%= form.label :status, "Feature Status " %>
                        <%= form.select :status, ["in_progress", "in_review"] %><br />
                      </div>
                    <% end %>
                  <% else %>
                    <div class="field">
                      <%= form.label :status, "Feature Status: "+ @feature.status %>
                    </div>
                  <% end %>
                <% end %>

                <% if current_user.role == "qa" %>
                  <% if @feature.status == "in_review"%>
                    <div class="field">
                      <%= form.label :status, "Feature Status " %>
                      <%= form.select :status, ["in_review", "complete"] %><br />
                    </div>
                  <% else %>
                    <div class="field">
                      <%= form.label :status, "Feature Status: "+ @feature.status %>
                    </div>
                  <% end %>
                <% end %>
                <div>
                  <%= form.submit "Update Feature", class: "btn btn-dark" %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/features/index.html.erb
<h1 class="mt-4 text-center">All Features</h1>
<hr />
<% if policy(Feature).index? %>
  <h5 class="container">
    <%= link_to "Create a feature", new_project_feature_path, class:
    "btn btn-primary" %>
  </h5>
<% end %>
<br />

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    All Features
  </div>

  <div class="card-body">
    <table id="datatablesSimple">
      <thead>
        <tr>
          <th>ID</th>
          <th>Feature Title</th>
          <th>Comment</th>
          <th>Feature Assigned to</th>
          <th>Feature Status</th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %> <% @features.each do |feature| %>

        <tr>
          <td><%= count = count+1 %></td>
          <td><%= feature.title %></td>
          <td><%= feature.comment %></td>
          <td><% temp = User.find(feature.user_id) %>
          <%= temp.email %></td>
          <td><%= feature.status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/features/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Create Feature</h3></div>
          <div class="card-body">
            <%= form_with model: ([@project, @feature]) do |form| %>
              <div>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
                <% @feature.errors.full_messages_for(:title).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <div>
                <%= form.label :comment %><br>
                <%= form.text_area :comment %><br>
                <% @feature.errors.full_messages_for(:comment).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>

              <% arr = Array.new %>
              <% @users.each do |u| %>
                <% if u.role == "developer" %>
                  <% arr.push(u.email) %>
                <% end %>
              <% end %>

              <div class="field">
                <%= form.label :user_id, "Feature Assigned To " %>
                <%= form.select :user_id, arr %><br />
              </div>

              <div>
                <%= form.submit "Create Feature", class: "btn btn-dark" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/features/show.html.erb
<h1 class="mt-4 text-center"><%= @feature.title %></h1>
<hr />
<% if policy(Feature).show? or @feature.status != "complete" %>
  <div class="d-flex justify-content-end">
    <%= link_to "Edit Feature", edit_project_feature_path, class: "btn btn-warning" %>
    &nbsp;&nbsp;&nbsp;
    <% if policy(Feature).show? %>
      <%= button_to "Delete Feature", project_feature_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>
<br />
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    Feature Info
  </div>
  <div class="card-body">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Feature Title</th>
          <th>Comment</th>
          <th>Feature Assigned to</th>
          <th>Feature Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @feature.title %></td>
          <td><%= @feature.comment %></td>
          <td><%= @feature.user.email %></td>
          <td><%= @feature.status %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>